SELECT
    M1.TGL,
    TO_CHAR(M1.TGL, 'YYYY') AS TAHUN,
    TO_CHAR(M1.TGL, 'MM') AS BULAN,
    O.DAY,
    O.DAY AS WORKDAY
FROM
    OUTLET F
JOIN RPT_MARKETING_SALES_1 M1 ON F.OUTLET_ID = M1.OUTLET_ID
JOIN RPT_MARKETING_SALES_2 M2 ON F.OUTLET_ID = M2.OUTLET_ID
JOIN RPT_MARKETING_SALES_3 M3 ON F.OUTLET_ID = M3.OUTLET_ID
JOIN OUTLET_PBI_T T ON F.OUTLET_ID = T.OUTLET_PBI
JOIN OUTLET_PBI_TS TS ON F.OUTLET_ID = TS.OUTLET_PBI
JOIN OUTLET_PBI_TV TV ON F.OUTLET_ID = TV.OUTLET_PBI
JOIN OUTLET_PBI_TSV TSV ON F.OUTLET_ID = TSV.OUTLET_PBI
JOIN OUTLET_PREF O ON F.OUTLET_ID = O.OUTLET_ID
WHERE ROWNUM <= 1000;

------------
---NEW WORKDAY FINAL(UBAH TGL STRING JADI TIMESTAMP) DARI KODE DI ATAS
CREATE OR REPLACE VIEW WORKDAY_ARIS AS
SELECT 
	TO_TIMESTAMP(TGL,'YYYY-MM-DD HH24:MI:SS.FF3') AS TGL,
	TAHUN,
	BULAN,
	DAY,
	WORKDAY
FROM TBL_WORKDAY tw      ; 