SELECT DATEGEN TGL, 
    TO_CHAR(DATEGEN,'YYYY') TAHUN,
    TO_CHAR(DATEGEN,'MM') BULAN,
    TO_CHAR(DATEGEN,'D') DAY,
    DECODE(TO_CHAR(DATEGEN,'D'),
         '1','FALSE','TRUE') WORKDAY FROM(
SELECT TO_DATE('01/01/2017','MM/DD/YYYY') + (ROWNUM - 1) DATEGEN
FROM ALL_OBJECTS
WHERE TO_DATE('01/01/2017','MM/DD/YYYY') + (ROWNUM - 1) <= TO_DATE('12/31/2024','MM/DD/YYYY'));